spring.application.name=backend
<<<<<<< milestone-3
 
=======

>>>>>>> main
spring.datasource.url=jdbc:mysql://localhost:3306/fixitnow?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
<<<<<<< milestone-3
 
=======

>>>>>>> main
server.port=8080